# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2297e7662cc4b014d5497903a4c518f736d8b60d0b8b3aa6853a5f21d30e33684fbfeac3808bd3bd95bd36c3c9872780419c3e9f2107140e2ed5622df7b98be0

test:
  secret_key_base: 3f1fcf4d34673c140f845ca1413836f81eb677329061babb4ca8523aff4fe090d927925b5d302f409e857550aa0586b791121c64ce3efc12be36c7cbdf819301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
